#!/bin/sh

set -e

cp -f /etc/skel/.config/examples/metadata.desktop /usr/share/plasma/desktoptheme/Orchis-dark/
cp -f /etc/skel/.config/examples/.profile /etc/skel/

 for u in /home/*
    do
        if ! test -f "${u}/.config/hypr/hyprland.conf"
        then
            cp -a /etc/skel/. "${u}/"
        fi

        if ! test -f "${u}/.config/ags/widgets/systray.js"
        then
            cp -af /etc/skel/.config/ags/. "${u}/.config/ags/"
        fi
    done

mkdir -p /etc/greetd/
cp -f /usr/share/pika/greetd/config.toml /etc/greetd/config.toml
rm /etc/systemd/system/display-manager.service
ln -s /lib/systemd/system/greetd.service /etc/systemd/system/display-manager.service
